from scripts.preprocessing.add_party_orientation_blocks import add_party_orientation_blocks
from scripts.preprocessing.remove_non_party_speeches import remove_non_party_speeches
from scripts.preprocessing.rename_party_duplicates import rename_party_duplicates
