from scripts.preprocessing.add_party_orientation_year_agenda import add_party_orientation_year_agenda
from scripts.preprocessing.remove_non_party_speeches import remove_non_party_speeches
from scripts.preprocessing.rename_party_duplicates import rename_party_duplicates
from scripts.preprocessing.remove_commentary import remove_commentary
from scripts.preprocessing.remove_duplicate_speeches import remove_duplicate_speeches
from scripts.preprocessing.remove_repeating_sentences import remove_repeating_greetings, remove_repeating_endings
from scripts.preprocessing.keep_relevant_legislation_years import keep_relevant_legislation_years